version: "3.7"
services:
  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bot
      MYSQL_USER: root
    volumes:
      - ./sql:/var/lib/mysql
      - ./src/:/docker-entrypoint-initdb.d/
  
  bot:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    logging:
      driver: "local"
      options:
        max-size: "50m"
    depends_on:
      - "db"
  
  updater:
    restart: always
    build: 
      context: .
      dockerfile: updater_dockerfile
    logging:
      driver: "local"
      options:
        max-size: "50m"
    depends_on:
      - "db"
  
  server:
    restart: always
    build:
      context: .
      dockerfile: server_dockerfile
    logging:
      driver: "local"
      options:
         max-size: "1m"
    ports:
      - "80:80"
    depends_on:
      - "db"
